-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 11:27:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema resly_temp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resly_temp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resly_temp` DEFAULT CHARACTER SET latin1 ;
USE `resly_temp` ;

-- -----------------------------------------------------
-- Table `resly_temp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`User` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `fname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `lname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `remember_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `avatar_url` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `role` TEXT(45) NULL DEFAULT NULL COMMENT '',
  `provider_id` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `provider_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Restaurant` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `restaurateur_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `location` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `description` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `opening_time` TIME NOT NULL COMMENT '',
  `closing_time` TIME NOT NULL COMMENT '',
  `telephone` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `address` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `restaurant_restaurateur_id_foreign` (`restaurateur_id` ASC)  COMMENT '',
  CONSTRAINT `restaurant_restaurateur_id_foreign`
    FOREIGN KEY (`restaurateur_id`)
    REFERENCES `resly_temp`.`User` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Table` (
  `table_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `restaurant_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `seats_number` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`table_id`)  COMMENT '',
  INDEX `table_restaurant_id_foreign` (`restaurant_id` ASC)  COMMENT '',
  CONSTRAINT `table_restaurant_id_foreign`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `resly_temp`.`Restaurant` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Booking` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `number_of_people` INT(11) NOT NULL COMMENT '',
  `booking_time` TIME NOT NULL COMMENT '',
  `booking_date` DATE NOT NULL COMMENT '',
  `diner_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `table_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `booking_table_id_foreign` (`table_id` ASC)  COMMENT '',
  CONSTRAINT `booking_table_id_foreign`
    FOREIGN KEY (`table_id`)
    REFERENCES `resly_temp`.`Table` (`table_id`),
  CONSTRAINT `diner_id`
    FOREIGN KEY (`id`)
    REFERENCES `resly_temp`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `category_name_unique` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Menu_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `description` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `price` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `cat_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `restaurant_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `menu_item_cat_id_foreign` (`cat_id` ASC)  COMMENT '',
  INDEX `menu_item_restaurant_id_foreign` (`restaurant_id` ASC)  COMMENT '',
  CONSTRAINT `menu_item_cat_id_foreign`
    FOREIGN KEY (`cat_id`)
    REFERENCES `resly_temp`.`Category` (`id`),
  CONSTRAINT `menu_item_restaurant_id_foreign`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `resly_temp`.`Restaurant` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `tag_name_unique` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`Menu_item_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`Menu_item_tag` (
  `menu_item_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `tag_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  INDEX `menu_item_tag_menu_item_id_foreign` (`menu_item_id` ASC)  COMMENT '',
  INDEX `menu_item_tag_tag_id_foreign` (`tag_id` ASC)  COMMENT '',
  CONSTRAINT `menu_item_tag_menu_item_id_foreign`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `resly_temp`.`Menu_item` (`id`),
  CONSTRAINT `menu_item_tag_tag_id_foreign`
    FOREIGN KEY (`tag_id`)
    REFERENCES `resly_temp`.`Tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`diner_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`diner_photo` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `diner_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `path` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `thumbnail_path` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `diner_id`
    FOREIGN KEY (`id`)
    REFERENCES `resly_temp`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `batch` INT(11) NOT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `resly_temp`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resly_temp`.`sessions` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `payload` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `last_activity` INT(11) NOT NULL COMMENT '',
  UNIQUE INDEX `sessions_id_unique` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
